### ISSUE TITLE
Optional use_native_unicode

### ISSUE THREAD

**Issue by bouke-nederstigt** [siddhantgoel/tornado-sqlalchemy#1]
Currently the option use_native_unicode is always added in the SessionFactory _setup method. However this config option isn't supported for mysql engines. It results in 

```TypeError: Invalid argument(s) 'use_native_unicode' sent to create_engine(), using configuration MySQLDialect_mysqldb/QueuePool/Engine```

I was able to solve the problem by creating my own factory that doesn't use the use_native_unicode option. I think it might be nice to only make this option available to pgsql engines to support other engines out of the box.

Let me know what you think. I don't mind implementing it.

**Comment by siddhantgoel** [comment]
Makes sense. How would you go about doing it? Plugging the option only when the `database_url` refers to a PostgreSQL URL?

**Comment by bouke-nederstigt** [comment]
Yes, exactly. I've created a pull request for it. #2

**Comment by siddhantgoel** [comment]
Merged. Thanks!
