### ISSUE TITLE
maybe the example code is wrong?

### ISSUE THREAD

**Issue by shllhs** [siddhantgoel/tornado-sqlalchemy#11]
```
class UsesSelfSessionRequestHandler(RequestHandler, SessionMixin):
     @coroutine
     def get(self):
         count = self.session.query(User).count()
         self.write('{} users so far!'.format(count))
```

Hi, i think this code in the tornado_web.py doesn't work correctly?Because SessionMixin appear in the second place, so UsesSelfSessionRequestHandler will use RequestHandler's on_finish method rather than SessionMixin's.After I change the order of RequestHandler and SessionMixin it work correctly

**Comment by siddhantgoel** [comment]
Thanks, just pushed a fix in https://github.com/siddhantgoel/tornado-sqlalchemy/commit/992264d390daf243d64fbd922fa9a5a42e24b0dd .
