### ISSUE TITLE
Sharing session context / Repository pattern

### ISSUE THREAD

**Issue by bouke-nederstigt** [siddhantgoel/tornado-sqlalchemy#3]
Hi,

For my project we heavily use the repository pattern to abstract database queries. These repositories use the session to connect to the database, and are usually injected into the handlers. 

The easiest solution to make sure the repositories use the correct session is to create them within the context of the request. So something like this. 

```class ExamplerHandler(JsonHandler, SessionMixin):
    def get(self, testId):
        with self.make_session() as session:
            self.repository = TestRepository(session)
```

However, I think it would be a better separation of concerns if the handlers aren't tasked with object creation themselves. In order to do this it would be necessary to somehow share the current context between the handlers and other objects (e.g. the repository). I think this might be possible using e.g. Tornado's stack context (see [Context local](https://github.com/viewfinderco/viewfinder/blob/master/backend/base/context_local.py) for an examle).

What are your thoughts on this?

**Comment by siddhantgoel** [comment]
1. How would the implementation look like? I haven't used StackContext in the past so I'm not too familiar with it. But would it be that you initialize a context before `get` is called and then tear it down after the request is handled? Or some other way?

2. What about creating a session for each request in the `tornado.web.RequestHandler.initialize` and tearing it down in `tornado.web.RequestHandler.finish`? This way the session would just be available for each handler and would be torn down when the request finishes. I guess you could then also initialize the repository independent of the actual handler functions. [raven-python](https://github.com/getsentry/raven-python/blob/master/raven/contrib/tornado/__init__.py#L239) seems to handle something like that this way.

**Comment by bouke-nederstigt** [comment]
1. Not completely sure yet what the StackContext implementation would look like. Kind of figuring it out right now, just wanted to see if you had any thoughts.

2. I did consider the  tying it to the request handler. But I think the async will also often be used in the context of websockets (it's definitely the case with my project anyway). In that situation it might not really make sense to connect it to a specific connection. Per message might be more logical. However it probably differs per use case. That's why I liked the context manager. It's most flexible from a developer perspective.

**Comment by siddhantgoel** [comment]
1. Hmm, I haven't used stack context in the past. I understand what they are, but I'm having a hard time visualizing how it would be used here. So please feel free to propose a solution - I'm open.
2. Good point. A context manager for this would be great.

**Comment by siddhantgoel** [comment]
Quick update. I've just added a `self.session` property in the latest version of `SessionMixin`. Accessing this property from your request handlers will lazily construct and return a new session. This hooks into tornado's `on_finish` entry point to commit and close the session when done. No session is created if you don't access this property (which should take care of the websocket issue you mentioned). Hope this helps!

**Comment by bouke-nederstigt** [comment]
Cool stuff! I'll see if I can find some time somewhere this week to update :)

**Comment by siddhantgoel** [comment]
@bouke-nederstigt I'm closing this issue. Please feel free to reopen if there are still open questions.

**Comment by gbgmian** [comment]
I have some callbacks in my tornado app which are not triggered from request handlers that need the session, as far as I understand tornado-sqlalchemy uses the request handler events (eg. `on_finish` to scope the session. Is there any way to use the session/SessionMixin in a safe way when not in a request handler?

Eg.

```
class MyClass(SessionMixin):
    def my_callback(self, obj_to_save):
        with self.make_session() as session:
            ...
```

**Comment by siddhantgoel** [comment]
You could of course use the `make_session` context manager which automatically closes the session when it's done. But at the moment there isn't anything specific for this use case, other than performing session handling yourself in your callback function. Are you scheduling the callbacks via the IOLoop?

**Comment by gbgmian** [comment]
I use an external async lib which relies heavily on callbacks for some operations. I tried using the make_session context manager directly from my callback similar to my example above, but gets the following error:

```
"venv/lib/python3.6/site-packages/tornado_sqlalchemy/__init__.py", line 150, in _make_session
    factory = self.application.settings.get('session_factory')
AttributeError: 'MyOrderCallback' object has no attribute 'application'
```

Do I need to supply the tornado app when creating my callback class or is there some more elegant way of making it work? Thanks a lot for your help and excellent work with this lib!

**Comment by siddhantgoel** [comment]
Ah, right, I forgot about that. At the moment unfortunately there's no elegant way of doing this.

You could pass the session factory object instead (from `self.application.settings.get('session_factory')`) in case you're creating your callback objects from within your request handlers, and then use the `make_session` function defined on the factory object to get a new session.

You would need to do the commit/rollback yourself then, and I'm not sure if that qualifies as elegant, but it should work. :)
