### ISSUE TITLE
TypeError: 'Test' object is not callable with as_future

### ISSUE THREAD

**Issue by PakitoSec** [siddhantgoel/tornado-sqlalchemy#47]
Hello,

With the following code below:  
```
  async def get(self, id):
        result = {}
        with self.make_session() as session:
            test = await tornado_sqlalchemy.as_future(session.query(schema.Test).get(id))

```

I have the following error: What is the problem ? is it a bug ? Sorry i'm new on asyncio.
```
Traceback (most recent call last):
  File "/home/admin/.virtualenvs/Env/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/home/admin/.virtualenvs/Env/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/mnt/hgfs/toto/tata/lib/server/apis/test_namespace/namespace.py", line 116, in get
    test = await tornado_sqlalchemy.as_future(session.query(schema.Test).get(id))
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
TypeError: 'Test' object is not callable
```

**Comment by siddhantgoel** [comment]
`session.query(schema.Test).get(id)` does not return a `sqlalchemy.orm.Query` object but your `Test` object instead, which is not callable.

If you really want to use async on this, maybe wrap the function in a callable (something like `get = lambda session.query(schema.Test).get(id)` and then pass `get` to `as_future`).

But in this case, the query is returning only one row so I would actually suggest not to bother with async at all and just do `test = session.query(schema.Test).get(id)` instead.
