### ISSUE TITLE
Propagate kwargs from SessionFactory constructor to create_engine

### ISSUE THREAD

**Issue by lincrosenbach** [siddhantgoel/tornado-sqlalchemy#76]
Kwargs is created empty for setting up the sqlalchemy create_engine this makes impossible to someone add specific settings for creating the engine.
An alternative would be to propagate from session factory kwargs. By doing that, it should allow any user to set all possible parameters like in:
https://docs.sqlalchemy.org/en/latest/core/engines.html#engine-creation-api

Issue reference:
https://github.com/siddhantgoel/tornado-sqlalchemy/blob/6a3f82aa687b848a518c7b3d5475cb34e1a0b08f/tornado_sqlalchemy/__init__.py#L135

**Comment by siddhantgoel** [comment]
I've actually been thinking of removing the custom arguments that `SessionFactory` defines (hence the warning when `session_events` and `engine_events` are present) and just defining the constructor as `def __init__(self, *args, **kwargs)` and then passing those arguments directly to SQLAlchemy's `create_engine`. Thoughts?

**Comment by lincrosenbach** [comment]
I like your proposed change. It would make more flexible but maybe backward compatibility may be compromised. Any use of it with positional arguments may break the API. Let me see if our colleagues have some thoughts about it. @igorcandeia @nicoddemus @kfasolin @igortg

**Comment by nicoddemus** [comment]
I don't see much problem in breaking backward compatibility here: if you are following [semantic versioning](https://semver.org/) then there are no backward compatibility guarantees for `0.x` versions.

**Comment by kfasolin** [comment]
I agree, since the definition on SQLAlchemy already is `sqlalchemy.create_engine(*args, **kwargs)` letting `*args, **kwargs` here makes it transparent to configure the engine the way its needed

**Comment by siddhantgoel** [comment]
Cool. I've requested an update to https://github.com/siddhantgoel/tornado-sqlalchemy/pull/78 .

**Comment by siddhantgoel** [comment]
Just merged #78 . I'll try to make another release in the next 2-3 days.

**Comment by lincrosenbach** [comment]
Solved on #78

**Comment by siddhantgoel** [comment]
Just pushed `v0.6.1`.
