### ISSUE TITLE
Is it thread-safe?

### ISSUE THREAD

**Issue by shaidiren** [siddhantgoel/tornado-sqlalchemy#8]
`self._pool = ThreadPoolExecutor(n)`
I learned that it use Multithreading to make task asynchronous, i'm not sure whether it's thread-safe

**Comment by siddhantgoel** [comment]
Every query is run on a separate, distinct session object (obtained via the `make_session` context manager). As far as my understanding goes, this is similar to having multiple session objects in a single threaded program. The problem would've been if queries were being run in parallel on the same session object, which is not the case here.

**Comment by shaidiren** [comment]
thanks you very much!
