### ISSUE TITLE
Upgrade Twine?

### ISSUE THREAD

**Issue by brainwane** [siddhantgoel/tornado-sqlalchemy#9]
Hi! I'm a [Twine](https://twine.readthedocs.io) maintainer; thanks for using Twine. I noticed you've pinned an old version of Twine in [your requirements file](https://github.com/siddhantgoel/tornado-sqlalchemy/blob/master/requirements.txt#L38). Twine [has changes in 1.11.0](https://twine.readthedocs.io/en/latest/changelog.html) that you might find useful, and I hope you'll upgrade. If you have any trouble upgrading, please do [let us know](https://github.com/pypa/twine/issues).

**Comment by siddhantgoel** [comment]
Hey, thanks for the heads up. I just pinned the version to 1.11.0 (https://github.com/siddhantgoel/tornado-sqlalchemy/commit/4ee0628a9372a9806f242ccdf70a8c2d3d2486bd). :sparkles:

**Comment by brainwane** [comment]
Thanks! I got [the libraries.io page](https://libraries.io/github/siddhantgoel/tornado-sqlalchemy) to re-sync so it's up to date now. :) And if you want, you can [now use Markdown descriptions for PyPI](https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi)!

**Comment by siddhantgoel** [comment]
Ah cool - didn't know that PyPI now supports Markdown. I'll consider changing the format, when I get tired of RST. :)
